[project]
name = 'fiesta_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.election_metadata]
path = 'contracts/election_metadata.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_comments]
path = 'contracts/file_comments.clar'
clarity_version = 2
epoch = 2.5

[contracts.scheduled_withdrawal_wallet]
path = 'contracts/scheduled_withdrawal_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage]
path = 'contracts/storage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
